name: buffalo_bar
description: "Buffalo Bar App."
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  go_router: ^14.2.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/mock_data/currentUser.json
    - assets/mock_data/scalps.json
    - assets/mock_data/user-02.json
    - assets/mock_data/user-03.json
    - assets/mock_data/group-01.json
    - assets/mock_data/group-02.json
    - assets/mock_data/groups.json
    - assets/mock_data/groupUsers.json
